from setuptools import setup

setup(name='premedy',
      version='0.0.1',
      description='Python Framework to handle Security Command Center Findings',
      url='http://github.com/premedy/premedy',
      author='Mauricio Wittenberg',
      author_email='mauricio.wittenber@premise.com',
      license='MIT',
      packages=['premedy', 'premedy/resources'],
      install_requires=[
          "goblet-gcp==0.10.3",
          "google-api-core==2.10.2",
          "google-api-python-client==2.65.0",
          "google-auth==2.13.0",
          "google-auth-httplib2==0.1.0",
          "google-cloud-access-context-manager==0.1.14",
          "google-cloud-appengine-logging==1.1.6",
          "google-cloud-asset==3.14.2",
          "google-cloud-audit-log==0.2.4",
          "google-cloud-core==2.3.2",
          "google-cloud-logging==3.2.5",
          "google-cloud-org-policy==1.4.1",
          "google-cloud-os-config==1.12.4",
          "google-cloud-securitycenter==1.16.2",
          "google-cloud-storage==2.5.0",
          "google-crc32c==1.5.0",
          "google-resumable-media==2.4.0",
          "googleapis-common-protos==1.56.4",
          "grpc-google-iam-v1==0.12.4",
          "pyparsing==3.0.9",
          "grpcio==1.50.0",
          "grpcio-status==1.50.0",
          "proto-plus==1.22.1",
          "protobuf==4.21.9",
          "slack-sdk==3.20.2"
      ],
      zip_safe=False)
